default: &default
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: <%=Rails.root + 'db/development.sqlite3'%>

test:
  <<: *default
  adapter: sqlite3
  database: <%=Rails.root + 'db/test.sqlite3'%>

production:
  <<: *default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 10 %>
  url: <%= ENV['DATABASE_URL'] %>
